services:
    auradb:
        image: neo4j:latest
        volumes:
            - ./auradb-data/logs:/logs
            - ./auradb-data/config:/config
            - ./auradb-data/data:/data
            - ./auradb-data/plugins:/plugins
        environment:
            - NEO4J_AUTH=neo4j/password
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4J_PLUGINS=["apoc", "graph-data-science"]
            - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*,jwt.security.*
            - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
            - NEO4J_server_memory_heap_initial__size=512M
            - NEO4J_server_memory_heap_max__size=1G
            - NEO4J_server_memory_pagecache_size=512M
        ports:
            - '7474:7474'
            - '7687:7687'
